name=roo_fonts_basic
version=1.0.1
author=Dejwk <dejwk.oss@gmail.com>
maintainer=Dejwk <dejwk.oss@gmail.com>
sentence=Collection of Noto fonts for use with dejwk/roo_display.
paragraph=See http://github.com/dejwk/roo_display.
category=Display
url=https://github.com/dejwk/roo_fonts_basic
architectures=*
depends=roo_display
